# -*- coding: utf-8 -*-
"""demo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDuirDfZAoQO_qJmwdQOGI4NsBEZkplR
"""

# Mad Libs Python Project

# Step 1: User se input lena
print("Mad Libs mein aapka swagat hai!")
adjective = input("Ek adjective daaliye (e.g., funny, silly): ")
noun = input("Ek noun daaliye (e.g., dog, car): ")
verb = input("Ek verb daaliye (e.g., run, dance): ")
place = input("Ek place daaliye (e.g., park, school): ")
animal = input("Ek animal daaliye (e.g., cat, elephant): ")

# Step 2: Story banayiye
story = f"Ek baar ki baat hai, ek {adjective} {noun} tha jo roz {verb} karta tha. Ek din woh {place} gaya aur wahan ek {animal} se mila. Dono dost ban gaye aur khush rehne lage."

# Step 3: Story print kijiye
print("\nAapki Mad Libs story:\n")
print(story)